---
# tasks file for filebeat

# ------Install filebeat--------


- name: Install filebeat
  apt:
   name: filebeat
   update_cache: yes

# ----- Replacing the configuration file

- name: Replace default filebeat configuration file
  template:
   src: filebeat.yml
   dest: /etc/filebeat/filebeat.yml

#--------- Adding a delay before starting filebeat service

- name: Pause before starting filebeat
  pause:
    seconds: 15  # Adjust the delay time as needed
    
#--------- Starting filebeat service

- name: Starting filebeat
  service:
   name: filebeat
   state: started
   enabled: yes
