---
# tasks file for kibana

# Installing Kibana

- name: Installing Kibana with apt
  apt:
   name: kibana
   update_cache: yes

- name: Ensure the certs directory exists
  ansible.builtin.file:
    path: /etc/kibana/certs
    state: directory
    mode: '0775'

- name: Copy certificate file
  copy:
    src: ../../files/elasticsearch-ca.pem
    dest: /etc/kibana/certs/

# Replacing default kibana.yml with updated file

- name: Replacing default kibana.yml with updated file
  template:
   src: kibana.yml
   dest: /etc/kibana/kibana.yml

# Starting Kibana

- name: Starting Kibana
  service:
   name: kibana
   state: started
   enabled: yes

