---
# defaults file for kibana

## server settings
server_port: 5601
server_host: 0.0.0.0
server_name: kibana

kibana_server_public_BaseUrl_protocol: "http"
kibana_server_public_BaseUrl_host: "192.168.1.13"
kibana_server_public_BaseUrl_port: 5601
kibana_server_public_BaseUrl: "{{ kibana_server_public_BaseUrl_protocol }}://{{ kibana_server_public_BaseUrl_host }}:{{ kibana_server_public_BaseUrl_port }}"


## elasticsearch hosts
elasticsearch_protocol: "https"
elasticsearch_port: 9200
elasticsearch_host_vm_1: "192.168.1.10"
elasticsearch_host_vm_2: "192.168.1.11"
elasticsearch_host_vm_3: "192.168.1.12"

elasticsearch_host_1: "{{ elasticsearch_protocol }}://{{ elasticsearch_host_vm_1 }}:{{ elasticsearch_port }}"
elasticsearch_host_2: "{{ elasticsearch_protocol }}://{{ elasticsearch_host_vm_2 }}:{{ elasticsearch_port }}"
elasticsearch_host_3: "{{ elasticsearch_protocol }}://{{ elasticsearch_host_vm_3 }}:{{ elasticsearch_port }}"


## xpack security settings

xpack_security_enabled: true

elasticsearch_ssl_certificateAuthorities: "/etc/kibana/certs/elasticsearch-ca.pem"

xpack_security_encryptionKey: adarsh