---
# defaults file for kibana

## server settings
server_port: 5601
server_host: 0.0.0.0
server_name: kibana

kibana_server_public_BaseUrl_protocol: "http"
# kibana_server_public_BaseUrl_host: "{{ kibana_host }}"
# kibana_server_public_BaseUrl_port: 5601
kibana_server_public_BaseUrl: "{{ kibana_server_public_BaseUrl_protocol }}://{{ kibana_host }}:{{ server_port }}"

## xpack security settings

xpack_security_enabled: true

elasticsearch_ssl_certificateAuthorities: "/etc/kibana/certs/elasticsearch-ca.pem"

# xpack_security_encryptionKey: adarsh