---
# tasks file for elasticsearch

# Installing Elasticsearch
- name: Installing Elasticsearch
  apt:
   name: elasticsearch

# Set unique node name
- name: Set unique node name
  set_fact:
    node_name: "elk-{{ ansible_play_hosts.index(inventory_hostname) + 1 }}"

- name: Ensure the certs directory exists
  ansible.builtin.file:
    path: /etc/elasticsearch/certs
    state: directory
    mode: '0777'

- name: Copy certificate file
  copy:
    src: ../../files/elastic-certificates.p12
    dest: /etc/elasticsearch/certs/

- name: Copy http p12
  copy:
    src: ../../files/http.p12
    dest: /etc/elasticsearch/certs/

# Replace default elasticsearch.yml
- name: Replace default elasticsearch.yml
  template:
   src: elasticsearch.yml
   dest: /etc/elasticsearch/elasticsearch.yml

# Start Elasticsearch service
- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: started
   enabled: yes

# Xpack security configuration 
- name: Including xpack security setup configuration
  include: security/keystore.yml