---
# This playbook will deploy ELK stack

- hosts: webservers
  become: yes
  vars_files:
  - ../vars/credentials.yml
  - ../vars/main.yml
  roles:
  - ../roles/webserver
  - ../roles/metricbeat
  - ../roles/filebeat
  - ../roles/config-beats-webserver