# This playbook will add Elastic Repo
- hosts: all
  become: yes
  roles:
  - ../roles/add-elastic-repo

# This playbook will deploy JDK
- hosts: elk
  become: yes
  vars_files: 
  - ../vars/credentials.yml
  - ../vars/main.yml

  roles:
  - ../roles/java
  - ../roles/elasticsearch
  - ../roles/kibana
  # - ../roles/metricbeat
  # - ../roles/filebeat
  # - ../roles/config-beats-elastic

# This playbook will deploy ELK stack
# - hosts: webservers
#   become: yes
#   vars_files:
#   - ../vars/credentials.yml
#   - ../vars/main.yml
#   roles:
#   - ../roles/webserver
#   - ../roles/metricbeat
#   - ../roles/filebeat
#   - ../roles/config-beats-webserver
