# This playbook will add Elastic Repo
- hosts: all
  become: yes
  roles:
  - ../roles/add-elastic-repo

# This playbook will deploy ELK
- hosts: elk
  become: yes
  vars_files: 
  - ../vars/credentials.yml
  - ../vars/main.yml

  roles:
  - ../roles/java
  - ../roles/elasticsearch

# This playbook will deploy ELK
- hosts: kibana
  become: yes
  vars_files: 
  - ../vars/credentials.yml
  - ../vars/main.yml

  roles:
  - ../roles/kibana